{% macro equipmaster_build(company) %}

WITH main_v1 AS (
    SELECT DISTINCT
        TRIM(B.CT020_7) AS MARA,
        TRIM(B.CT020_5) AS MACNO,
        TRIM(B.CT020_6) AS MARATYPE,
        CONCAT(A.CT010_1, A.CT010_2, A.CT010_3) AS CTNO,
        CT010_4 AS CONTRACT_TYPE,
        A.CT010_11 AS CCUSTNO,
        B.CT020_11 AS DCUSTNO,
        A.CT010_12A AS CTDPT,
        CT020_12 AS SDPT,
        A.CT010_21 AS C_SDATE,
        CASE WHEN A.CT010_26 != '' AND A.CT010_26 IS NOT NULL THEN A.CT010_26 ELSE A.CT010_22 END AS C_EDATE,
        B.CT020_3B AS SONO,
        B.CT020_15 AS DELV_DATE,
        B.CT020_37 AS ESTIMATED_COST_PER_BLACK_PAGE,
        B.CT020_38 AS ESTIMATED_COST_PER_COLOR_PAGE,
        CT020_33 AS MAINTENANCE_INTERVAL,
        CASE WHEN CT020_51 >= 0 THEN CT020_51 ELSE CT010_51 END AS METER_READING_INTERVAL,
        B.CT020_3C AS SERIAL_NO,
        PARSE_DATE('%Y%m%d', GREATEST(A.CT010_21, B.CT020_15)) AS START_DT,
        PARSE_DATE('%Y%m%d', MIN(B.CT020_15) OVER (PARTITION BY CONCAT(A.CT010_1, A.CT010_2, A.CT010_3))) AS ctno_delv_dt,
        B.CT020_52 AS BILLING_METHOD,
        B.CT020_54 AS BASIC_RENT_MACHINE,
        0 AS BASIC_RENT_PERIPHERAL,
        B.CT020_52A AS BILLING_METHOD_PRINT,
        B.CT020_53AC AS MONTHLY_FEE_BLACK,
        B.CT020_53C AS MONTHLY_FEE_COLOR,
        B.CT020_53 AS MONTHLY_FEE_BLACK_COLOR,
        B.CT020_56 AS BASIC_PRINT_VOLUME_BLACK,
        B.CT020_57 AS BASIC_PRINT_VOLUME_COLOR,
        B.CT020_36A AS ESTIMATED_MONTHLY_PRINT_VOLUME_COLOR,
        B.CT020_36 AS ESTIMATED_MONTHLY_PRINT_VOLUME_BLACK,
        B.CT020_58 AS BILLING_COLOR
    FROM {{ ref('stg_' ~ company ~ '_ct010dl') }} A
    JOIN {{ ref('stg_' ~ company ~ '_ct020dl') }} B
        ON CONCAT(A.CT010_1, A.CT010_2, A.CT010_3) = CONCAT(B.CT020_1, B.CT020_2, B.CT020_3)
    WHERE CT010_81 = 'Y'
),

main AS (
    SELECT
        m.*,
        STOPDT,
        STOPRN,
        DEVICEST,
        CONTRACTST,
        RESTOCK_DT,
        CASE
            WHEN COUNT(CASE WHEN RESTOCK_DT IS NULL OR RESTOCK_DT = '' THEN 1 END) OVER (PARTITION BY m.CTNO) > 0
            THEN NULL
            ELSE MAX(RESTOCK_DT) OVER (PARTITION BY m.CTNO)
        END AS ctno_stop_dt,
        GREATEST(ctno_delv_dt, PARSE_DATE('%Y%m%d', C_SDATE)) AS ctno_start_dt
    FROM main_v1 AS m
    LEFT JOIN (
        SELECT DISTINCT
            TRIM(MARA) AS MARA,
            TRIM(CTNO) AS CTNO,
            TRIM(MACNO) AS MACNO,
            STOPDT,
            STOPRN,
            DEVICEST,
            CONTRACTST,
            RESTOCK_DT
        FROM {{ ref('stg_' ~ company ~ '_ct020bv2dl') }}
    ) AS v2
        ON m.CTNO = TRIM(v2.CTNO) AND m.MARA = TRIM(v2.MARA) AND m.MACNO = TRIM(v2.MACNO)
    WHERE (STOPDT IS NULL OR STOPDT = '')
       OR PARSE_DATE('%Y%m%d', STOPDT) >= DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH), MONTH)
),

period_duration AS (
    SELECT
        MARA,
        MACNO,
        CTNO,
        -- 合約期數
        DATE_DIFF(PARSE_DATE('%Y%m%d', C_EDATE), PARSE_DATE('%Y%m%d', C_SDATE), MONTH)
            + IF(EXTRACT(DAY FROM PARSE_DATE('%Y%m%d', C_SDATE)) <= EXTRACT(DAY FROM PARSE_DATE('%Y%m%d', C_EDATE)), 1, 0)
            AS CTNO_PERIOD,
        -- 合約已執行期數
        DATE_DIFF(
            CASE WHEN ctno_stop_dt != '' AND ctno_stop_dt IS NOT NULL
                THEN PARSE_DATE('%Y%m%d', ctno_stop_dt)
                ELSE LAST_DAY(DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH), MONTH)
            END,
            ctno_start_dt,
            MONTH
        ) + IF(
            EXTRACT(DAY FROM ctno_start_dt) <= EXTRACT(DAY FROM
                CASE WHEN ctno_stop_dt != '' AND ctno_stop_dt IS NOT NULL
                    THEN PARSE_DATE('%Y%m%d', ctno_stop_dt)
                    ELSE LAST_DAY(DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH), MONTH)
                END
            ), 1, 0
        ) AS CTNO_DURATION,
        -- 機台已執行期數
        DATE_DIFF(
            CASE WHEN RESTOCK_DT != '' AND RESTOCK_DT IS NOT NULL
                THEN PARSE_DATE('%Y%m%d', RESTOCK_DT)
                ELSE LAST_DAY(DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH), MONTH)
            END,
            START_DT,
            MONTH
        ) + IF(
            EXTRACT(DAY FROM START_DT) <= EXTRACT(DAY FROM
                CASE WHEN RESTOCK_DT != '' AND RESTOCK_DT IS NOT NULL
                    THEN PARSE_DATE('%Y%m%d', RESTOCK_DT)
                    ELSE LAST_DAY(DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH), MONTH)
                END
            ), 1, 0
        ) AS MACNO_DURATION
    FROM main
),

EQ AS (
    SELECT DISTINCT
        TRIM(EQ010_1) AS MACNO,
        TRIM(EQ010_3) AS MARA,
        MACID,
        TRIM(SO_NO1) AS SONO
    FROM {{ ref('stg_' ~ company ~ '_eq010dl') }}
    WHERE SO_NO1 != ''
),

CT020B AS (
    SELECT * FROM (
        SELECT DISTINCT
            CTNO,
            MACNO,
            MARA,
            LOSERN,
            LOSERSNOTHER,
            OTHERBRAND,
            OTHERBRANDNAME,
            ROW_NUMBER() OVER (
                PARTITION BY CTNO, MACNO, MARA
                ORDER BY DEVICEST ASC,
                    LENGTH(TRIM(LOSERSNOTHER)) DESC,
                    LENGTH(TRIM(LOSERN)) DESC,
                    LENGTH(TRIM(OTHERBRAND)) DESC,
                    LENGTH(TRIM(OTHERBRANDNAME)) DESC
            ) AS rn
        FROM {{ ref('stg_' ~ company ~ '_ct020bv2dl') }}
        WHERE LOSERN IS NOT NULL AND LOSERN != ''
    )
    WHERE rn = 1
),

SD022DL AS (
    SELECT DISTINCT
        TRIM(ORIGIN_AGRE) AS CTNO,
        TRIM(SO_NO) AS SONO,
        TRIM(CUSTNO) AS CUSTNO,
        CT010_61 AS MERGED_BILLING_METHOD,
        CT010_69 AS ERROR_RATE
    FROM {{ ref('stg_' ~ company ~ '_sd022dl') }}
),

PERIPHERAL AS (
    SELECT
        RTRIM(SO_NO) AS SONO,
        LEFT(SERIAL_NO, 2) AS SERIAL_GROUP,
        SUM(CT020_54) AS BASIC_RENT_PERIPHERAL_SUM
    FROM {{ ref('stg_' ~ company ~ '_sd023dl') }}
    WHERE RIGHT(SERIAL_NO, 2) != '01'
    GROUP BY 1, 2
),

SD023 AS (
    SELECT DISTINCT
        TRIM(MACNO) AS MACNO,
        TRIM(MARA) AS MARA,
        RTRIM(a.SO_NO) AS SONO,
        a.SERIAL_NO,
        a.CT020_52 AS BILLING_METHOD,
        a.CT020_54 AS BASIC_RENT_MACHINE,
        b.BASIC_RENT_PERIPHERAL_SUM AS BASIC_RENT_PERIPHERAL,
        a.TG_TYPE AS BILLING_METHOD_PRINT,
        a.CT020_53AC AS MONTHLY_FEE_BLACK,
        a.CT020_53C AS MONTHLY_FEE_COLOR,
        a.CT020_53 AS MONTHLY_FEE_BLACK_COLOR,
        a.CT020_56 AS BASIC_PRINT_VOLUME_BLACK,
        a.CT020_57 AS BASIC_PRINT_VOLUME_COLOR,
        a.CT020_36A AS ESTIMATED_MONTHLY_PRINT_VOLUME_COLOR,
        a.CT020_36 AS ESTIMATED_MONTHLY_PRINT_VOLUME_BLACK,
        a.CT020_58 AS BILLING_COLOR
    FROM {{ ref('stg_' ~ company ~ '_sd023dl') }} a
    LEFT JOIN PERIPHERAL b
        ON LEFT(a.SERIAL_NO, 2) = b.SERIAL_GROUP AND RTRIM(a.SO_NO) = b.SONO
    WHERE RIGHT(a.SERIAL_NO, 2) = '01'
),

MM000 AS (
    SELECT DISTINCT LEFT(MARAGRP, 3) AS MARAGRP_PREFIX, MARA
    FROM {{ ref('stg_' ~ company ~ '_mm000dl') }}
    WHERE LEFT(MARAGRP, 3) IN ('MAC', 'MBA')
)

SELECT DISTINCT
    m.MARA,
    m.MACNO,
    m.MARATYPE,
    m.CTNO,
    m.SONO,
    MACID,
    CONTRACTST AS CSTATUS,
    CCUSTNO,
    DCUSTNO,
    CTDPT,
    SDPT,
    C_SDATE,
    C_EDATE,
    STOPDT,
    STOPRN,
    DEVICEST AS STOPST,
    LOSERN,
    LOSERSNOTHER,
    OTHERBRAND,
    OTHERBRANDNAME,
    DELV_DATE,
    MERGED_BILLING_METHOD,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.BILLING_METHOD ELSE d.BILLING_METHOD END AS BILLING_METHOD,
    CONTRACT_TYPE,
    MAINTENANCE_INTERVAL,
    METER_READING_INTERVAL,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.BASIC_RENT_MACHINE ELSE d.BASIC_RENT_MACHINE END AS BASIC_RENT_MACHINE,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.BASIC_RENT_PERIPHERAL ELSE d.BASIC_RENT_PERIPHERAL END AS BASIC_RENT_PERIPHERAL,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.BILLING_METHOD_PRINT ELSE d.BILLING_METHOD_PRINT END AS BILLING_METHOD_PRINT,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.MONTHLY_FEE_BLACK ELSE d.MONTHLY_FEE_BLACK END AS MONTHLY_FEE_BLACK,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.MONTHLY_FEE_COLOR ELSE d.MONTHLY_FEE_COLOR END AS MONTHLY_FEE_COLOR,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.MONTHLY_FEE_BLACK_COLOR ELSE d.MONTHLY_FEE_BLACK_COLOR END AS MONTHLY_FEE_BLACK_COLOR,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.BASIC_PRINT_VOLUME_BLACK ELSE d.BASIC_PRINT_VOLUME_BLACK END AS BASIC_PRINT_VOLUME_BLACK,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.BASIC_PRINT_VOLUME_COLOR ELSE d.BASIC_PRINT_VOLUME_COLOR END AS BASIC_PRINT_VOLUME_COLOR,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.ESTIMATED_MONTHLY_PRINT_VOLUME_COLOR ELSE d.ESTIMATED_MONTHLY_PRINT_VOLUME_COLOR END AS ESTIMATED_MONTHLY_PRINT_VOLUME_COLOR,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.ESTIMATED_MONTHLY_PRINT_VOLUME_BLACK ELSE d.ESTIMATED_MONTHLY_PRINT_VOLUME_BLACK END AS ESTIMATED_MONTHLY_PRINT_VOLUME_BLACK,
    ERROR_RATE,
    CASE WHEN m.SONO = '' OR m.SONO IS NULL THEN m.BILLING_COLOR ELSE d.BILLING_COLOR END AS BILLING_COLOR,
    ESTIMATED_COST_PER_BLACK_PAGE,
    ESTIMATED_COST_PER_COLOR_PAGE,
    p.CTNO_PERIOD,
    -- 合約已執行期數（到期解約修正）
    GREATEST(
        CASE
            WHEN STOPRN = '到期解約' AND (p.CTNO_DURATION - p.CTNO_PERIOD = 0) THEN p.CTNO_DURATION
            WHEN STOPRN = '到期解約' AND (p.CTNO_DURATION - p.CTNO_PERIOD = 1) THEN p.CTNO_DURATION - 1
            WHEN STOPRN = '到期解約' AND (p.CTNO_DURATION - p.CTNO_PERIOD > 1) THEN p.CTNO_DURATION
            ELSE p.CTNO_DURATION
        END, 0
    ) AS CTNO_DURATION,
    -- 機台已執行期數（到期解約 + 回收修正）
    GREATEST(
        CASE
            WHEN (RESTOCK_DT IS NOT NULL AND RESTOCK_DT != '')
                AND (STOPDT IS NULL OR STOPDT = '')
                AND (STOPRN IS NULL OR STOPRN = '')
                AND (p.MACNO_DURATION - p.CTNO_PERIOD = 1)
            THEN p.CTNO_PERIOD
            WHEN STOPRN = '到期解約' AND (p.MACNO_DURATION - p.CTNO_PERIOD = 0) THEN p.MACNO_DURATION
            WHEN STOPRN = '到期解約' AND (p.MACNO_DURATION - p.CTNO_PERIOD = 1) THEN p.MACNO_DURATION - 1
            WHEN STOPRN = '到期解約' AND (p.MACNO_DURATION - p.CTNO_PERIOD > 1) THEN p.MACNO_DURATION
            ELSE p.MACNO_DURATION
        END, 0
    ) AS MACNO_DURATION,
    d.SERIAL_NO,
    RESTOCK_DT,
    CURRENT_DATE() AS ETL_DT
FROM main m
LEFT JOIN period_duration AS p ON m.MARA = p.MARA AND m.MACNO = p.MACNO AND m.CTNO = p.CTNO
LEFT JOIN CT020B c ON m.CTNO = c.CTNO AND m.MARA = c.MARA AND m.MACNO = c.MACNO
LEFT JOIN SD022DL s ON m.SONO = s.SONO AND m.DCUSTNO = s.CUSTNO
LEFT JOIN SD023 d
    ON m.MARA = d.MARA
    AND m.SONO = d.SONO
    AND (
        m.MACNO = d.MACNO
        OR LEFT(m.SERIAL_NO, 4) = d.SERIAL_NO
        OR LEFT(REPLACE(m.SERIAL_NO, m.SONO, ''), 4) = d.SERIAL_NO
    )
LEFT JOIN EQ AS e ON m.MARA = e.MARA AND m.MACNO = e.MACNO AND m.SONO = e.SONO
LEFT JOIN MM000 AS f ON m.MARA = f.MARA
WHERE f.MARA IS NOT NULL
    AND ((STOPDT IS NULL OR STOPDT = '')
        OR PARSE_DATE('%Y%m%d', STOPDT) >= DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH), MONTH))

{% endmacro %}
