{% macro stg_consump_detail(source_name) %}

SELECT
    CAST(MARA AS STRING) AS MARA,
    CAST(MACNO AS STRING) AS MACNO,
    CAST(CTNO AS STRING) AS CTNO,
    CAST(POSTDATE AS STRING) AS POSTDATE,
    CAST(DOCNO AS STRING) AS DOCNO,
    CAST(NDOCNO AS STRING) AS NDOCNO,
    CAST(DOCNO_TYPE AS STRING) AS DOCNO_TYPE,
    CAST(ITEM_MARA AS STRING) AS ITEM_MARA,
    CAST(ITEM_MARADESC AS STRING) AS ITEM_MARADESC,
    CAST(MARAGRP AS STRING) AS MARAGRP,
    SAFE_CAST(DILQTY AS INT64) AS DILQTY,
    SAFE_CAST(HEAD_COST AS NUMERIC) AS HEAD_COST,
    SAFE_CAST(DPT_COST AS NUMERIC) AS DPT_COST,
    SAFE_CAST(BLACK_COUNTER AS INT64) AS BLACK_COUNTER,
    SAFE_CAST(COLOR_COUNTER AS INT64) AS COLOR_COUNTER,
    CAST(ETL_DT AS STRING) AS ETL_DT
FROM {{ source(source_name, 'consump_detail') }}

{% endmacro %}
