{% macro stg_ct020bv2dl(source_name) %}

SELECT
    CAST(MARA AS STRING) AS MARA,
    CAST(CTNO AS STRING) AS CTNO,
    CAST(MACNO AS STRING) AS MACNO,
    CAST(STOPDT AS STRING) AS STOPDT,
    CAST(STOPRN AS STRING) AS STOPRN,
    CAST(DEVICEST AS STRING) AS DEVICEST,
    CAST(CONTRACTST AS STRING) AS CONTRACTST,
    CAST(RESTOCK_DT AS STRING) AS RESTOCK_DT,
    CAST(LOSERN AS STRING) AS LOSERN,
    CAST(LOSERSNOTHER AS STRING) AS LOSERSNOTHER,
    CAST(OTHERBRAND AS STRING) AS OTHERBRAND,
    CAST(OTHERBRANDNAME AS STRING) AS OTHERBRANDNAME
FROM {{ source(source_name, 'ct020bv2dl_new') }}

{% endmacro %}
